# Exclude patterns
exclude: |
  (?x)(
    ^venv/|
    ^env/|
    ^.venv/|
    ^.env/|
    ^node_modules/|
    ^frontend/node_modules/|
    ^.git/|
    ^.pytest_cache/|
    ^__pycache__/|
    ^.coverage/|
    ^htmlcov/|
    ^dist/|
    ^build/|
    ^.next/
  )

repos:
  # Python formatting and linting
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v5.0.0
    hooks:
      - id: trailing-whitespace
        stages: [pre-commit]
      - id: end-of-file-fixer
        stages: [pre-commit]
      - id: check-yaml
        stages: [pre-commit]
      - id: check-added-large-files
        args: ["--maxkb=1000"]
        stages: [pre-commit]
      - id: check-merge-conflict
        stages: [pre-commit]
      - id: debug-statements
        stages: [pre-commit]

  # Python code formatting
  - repo: https://github.com/psf/black
    rev: 25.1.0
    hooks:
      - id: black
        language_version: python3
        stages: [pre-commit]

  # Python import sorting
  - repo: https://github.com/pycqa/isort
    rev: 6.0.1
    hooks:
      - id: isort
        args: ["--profile", "black"]
        stages: [pre-commit]

  # Python linting
  - repo: https://github.com/charliermarsh/ruff-pre-commit
    rev: v0.11.5
    hooks:
      - id: ruff
        args: [--fix, --exit-non-zero-on-fix]
        stages: [pre-commit]

  # TypeScript/JavaScript linting
  # Temporarily disabled until properly configured
  # - repo: https://github.com/pre-commit/mirrors-eslint
  #   rev: v9.0.0-beta.2
  #   hooks:
  #     - id: eslint
  #       files: \.(js|ts|tsx)$
  #       types: [file]
  #       stages: [pre-commit]
  #       additional_dependencies:
  #         - eslint@9.0.0-beta.2
  #         - eslint-plugin-react@7.34.1
  #         - eslint-plugin-react-hooks@5.0.0-canary-7118f5dd7-20230705
  #         - typescript@5.7.2
  #         - "@typescript-eslint/eslint-plugin@8.22.0"
  #         - "@typescript-eslint/parser@8.22.0"

  # Conventional commit message validation
  - repo: https://github.com/commitizen-tools/commitizen
    rev: v4.5.1
    hooks:
      - id: commitizen
        stages: [commit-msg]
