"""Add is_superadmin field and coordinate formats

Revision ID: 93dc3498f79f
Revises: 7fb8d720a5d7
Create Date: 2025-04-06 15:25:24.712313

"""

from typing import Sequence, Union



# revision identifiers, used by Alembic.
revision: str = "93dc3498f79f"
down_revision: Union[str, None] = "7fb8d720a5d7"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
