name: Pull Request Validation

on:
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  validate-pr:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
      with:
        fetch-depth: 0
    
    - name: Check commit message format
      run: |
        # Get all commit messages in the PR
        git log --format=%B origin/${{ github.base_ref }}..HEAD > commit_messages.txt
        
        # Check if any commit message doesn't follow the conventional commit format
        if ! grep -E "^(feat|fix|docs|style|refactor|perf|test|build|ci|chore|revert)(\([a-z-]+\))?: .{1,}" commit_messages.txt; then
          echo "Error: Commit messages should follow the Conventional Commits format."
          echo "Example: feat(auth): add login functionality"
          echo "See https://www.conventionalcommits.org/ for more details."
          exit 1
        fi
    
    - name: Validate PR title
      uses: amannn/action-semantic-pull-request@v5
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        types: |
          feat
          fix
          docs
          style
          refactor
          perf
          test
          build
          ci
          chore
          revert
    
    - name: Check for large files
      run: |
        # Find files larger than 10MB
        large_files=$(find . -type f -size +10M -not -path "*/node_modules/*" -not -path "*/venv/*" -not -path "*/.git/*")
        
        if [ -n "$large_files" ]; then
          echo "Error: The following files are larger than 10MB:"
          echo "$large_files"
          echo "Please remove these files or add them to .gitignore."
          exit 1
        fi
